### ISSUE TITLE
npm package not registered

### ISSUE THREAD

**Issue by floretan** [platformsh/platformsh-client-js#1]
Running `npm install platformsh-client` as indicated in the documentation doesn't work, the package is node registered.

```
$ npm install platformsh-client
npm ERR! code E404
npm ERR! 404 Not Found: platformsh-client@latest

**Comment by ydeshayes** [comment]
Hello,

I've just publish the lib to npm, you can retry to install it.

**Comment by floretan** [comment]
Thanks you!
